# Build settings
github: [metadata]
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
paginate: 5
paginate_path: "/blog/page/:num/"
sass:
  style: compressed
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty

# site settings
title: duszekmestre
email: admin@duszekmestre.pl
description: >- # this means to ignore newlines until "baseurl:"
  duszekmestre.pl
  Łukasz Arciszewski
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://duszekmestre.pl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: larciszewski
github_username:  duszekmestre

date_format: "%b %-d, %Y"

# features switches
show_social_icons:    true

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-73307349-1
google_tag_manager:

# Social icons
github_username: duszekmestre
stackoverflow_id: 1910057
twitter_username:
linkedin_username: larciszewski
medium_id:

# SEO
twitter:
  username: larciszewski
  card: summary
social:
  name: duszekmestre Łukasz Arciszewski
  links:
    - https://twitter.com/larciszewski
    - https://www.linkedin.com/in/larciszewski
    - https://github.com/duszekmestre
lang: en_US

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor